// src/ui/svelte/CLBTier.svelte
<script lang="ts">
	import CLBSkeleton from './CLBSkeleton.svelte'

	export let title: string
	export let subtitle: string
	export let media: string
</script>

<div class="clb-tier">
	{#if media}
		<img
			src={media}
			class="clb-tier__media"
			alt={`Media file of the ${title} badge.`}
		/>
	{/if}
	{#if !media}
		<CLBSkeleton class="min-h-[16rem] w-full" />
	{/if}
	<div class="mb-2 grid">
		<div class="clb-tier__title">{title}</div>
		<div class="clb-tier__subtitle">{subtitle}</div>
	</div>
	{#if $$slots.default}
		<div class="clb-tier__actions">
			<slot />
		</div>
	{/if}
</div>

// src/ui/react/CLBTier/index.tsx
import React from 'react';
import CLBSkeleton from './CLBSkeleton';
import './style.scss';

interface CLBTierProps {
	title: string;
	subtitle?: string;
	media?: string;
	children?: React.ReactNode|string;
}

const CLBTier: React.FC<CLBTierProps> = ({title, subtitle, media, children}) => {
	return (
		<div className="clb-tier">
			{media &&
				<img
					src="media"
					className="clb-tier__media"
					alt={`Media file of the ${ title } badge.`}
				/>
			}
			{!media &&
				<CLBSkeleton />
			}
			<div className="mb-2 grid">
				<div className="clb-tier__title">{title}</div>
				<div className="clb-tier__subtitle">{subtitle}</div>
			</div>
			{children &&
				<div className="clb-tier__actions">
					{children}
				</div>
			}
		</div>
  );
};

export default CLBTier;
