// src/ui/react/CLBButton/index.tsx
import React from 'react';
import './overrides.scss';

type ButtonVariant = 'outlined' | 'filled';
type ButtonState = 'success' | 'warning' | 'danger' | 'disabled';
type ButtonType = ButtonVariant | ButtonState | `${ButtonVariant} ${ButtonState}`;

interface CLBButtonProps {
	type?: ButtonType|string;
	icon?: React.ReactElement|string;
	link?: string;
	onClick?: () => React.MouseEventHandler|void;
	children?: React.ReactNode|string;
	isDisabled?: boolean;
}

const CLBButton: React.FC<CLBButtonProps> = ({icon, type, link, isDisabled, onClick, children }) => {
	const ButtonBase: React.ReactNode = (
		<>
			{icon && <i className='hs-button__icon'>{icon}</i>}
			{<span className='hs-button__label'>{children}</span>}
		</>
	);

	const _assertType = (type: string): string => {
		const finalTypes: string[] = [];
		type.split(' ').forEach((type) => {
			finalTypes.push('is-' + type);
		});
		return finalTypes.join(' ');
	};

	if (!link || onClick) {
		return (
			<button
				className={`hs-button${type ? ' ' + _assertType(type) : ''}`}
				onClick={onClick}
				disabled={isDisabled}
			>
				{ButtonBase}
			</button>
		);
	}

	const isLinkExternal: boolean = !!(link.startsWith('http://') || link.startsWith('https://'));

	return (
		<a
			href={link}
			className={`hs-button${type ? ' ' + _assertType(type) : ''}`}
			target={isLinkExternal ? '_blank' : '_self'}
		>
			{ButtonBase}
		</a>
	);
};

export default CLBButton;

// src/ui/vue/CLBButton.vue
<template>
	<button
		v-if="!link"
		v-bind:class="`hs-button${type && ' ' + assertType(type)}`"
		role="button"
		:disabled="isDisabled"
	>
		<i v-if="isIconVisible" class="hs-button__icon"
			><slot name="icon"></slot
		></i>
		<span v-if="isLabelVisible" class="hs-button__label"><slot></slot></span>
	</button>

	<a
		v-else
		v-bind:class="`hs-button${type && ' ' + assertType(type)}`"
		role="link"
		:[href]="link"
		:target="assertTarget(link)"
	>
		<i v-if="isIconVisible" class="hs-button__icon"
			><slot name="icon"></slot
		></i>
		<span v-if="isLabelVisible" class="hs-button__label"><slot></slot></span>
	</a>
</template>

<script>
import { Comment } from 'vue'
export default {
	name: 'HSButton',
	props: {
		link: {
			type: String,
			default: null,
		},
		isDisabled: {
			type: Boolean,
			default: false,
		},
		type: {
			type: String,
			default: '',
		},
	},
	computed: {
		isLabelVisible() {
			return (
				this.$slots.default &&
				this.$slots.default().findIndex((o) => o.type !== Comment) !== -1
			)
		},
		isIconVisible() {
			return (
				this.$slots.icon &&
				this.$slots.icon().findIndex((o) => o.type !== Comment) !== -1
			)
		},
		href() {
			return this.isDisabled ? null : 'href'
		},
	},
	methods: {
		assertType(type) {
			const finalTypes = []
			type.split(' ').forEach((type) => {
				finalTypes.push('is-' + type)
			})
			return finalTypes.join(' ')
		},
		assertTarget(link) {
			const _isExternalLink = (link) =>
				!!(link.startsWith('http://') || link.startsWith('https://'))
			return _isExternalLink(link) ? '_blank' : '_self'
		},
	},
}
</script>

<style lang="scss" scoped>
// Alterations
.hs-button {
	--hs-button-width: auto;
	flex-flow: row nowrap;
}
</style>
