// src/ui/svelte/CLBButtonGroupItem.svelte
<input id={id} type="radio" name={name} value={value} checked={isChecked} disabled={isDisabled}>
<label for={id} class={`hs-button is-outlined${isDisabled ? ' is-disabled' : ''}`}>
	<span class="hs-button__label"><slot /></span>
</label>

<script lang="ts">
	export let id: string;
	export let name: string;
	export let value: string;
	export let isChecked: boolean;
	export let isDisabled: boolean;
</script>

// src/ui/vue/CLBButtonGroupItem.vue
<template>
  <input :id="id" type="radio" :name="name" :value="value" :checked="isChecked" :disabled="isDisabled">
  <label :for="id" :class="`hs-button is-outlined${isDisabled ? ' is-disabled' : ''}`">
  	<span class="hs-button__label"><slot /></span>
	</label>
</template>

<script lang="ts">
export default {
  name: 'CLBButtonGroupItem',
	props: {
		id: String,
		name: String,
		value: String,
		isChecked: Boolean,
		isDisabled: Boolean,
	}
}
</script>
