// src/ui/svelte/CLBButton.svelte
<script lang="ts">
	import { handleTarget, handleVariants } from '../lib'

	export let link: string | null
	export let type: string | null
	export let isDisabled: boolean = false
	export let onClick: () => void
	export let nativeType: string | null

	function _assertType(type: string): string {
		return handleVariants(type)
	}

	const _linkTarget: string = link ? handleTarget(link) : ''
</script>

{#if !link}
	<button
		class={`hs-button${type ? ' ' + _assertType(type) : ''}`}
		{onClick}
		disabled={isDisabled}
		type={nativeType}
	>
		{#if $$slots.icon}
			<i class="hs-button__icon">
				<slot name="icon" />
			</i>
		{/if}
		{#if $$slots}
			<span class="hs-button__label"><slot /></span>
		{/if}
	</button>
{:else}
	<a
		class={`hs-button${type ? ' ' + _assertType(type) : ''}`}
		{onClick}
		href={link}
		target={_linkTarget}
	>
		{#if $$slots.icon}
			<i class="hs-button__icon">
				<slot name="icon" />
			</i>
		{/if}
		{#if $$slots}
			<span class="hs-button__label"><slot /></span>
		{/if}
	</a>
{/if}

// src/ui/vue/CLBButton.vue
<template>
	<button
			v-if="!link"
			v-bind:class="`hs-button${type && ' ' + assertType(type)}`"
			role="button"
			:disabled="isDisabled"
	>
		<i v-if="isIconVisible" class="hs-button__icon"
		><slot name="icon"></slot
		></i>
		<span v-if="isLabelVisible" class="hs-button__label"><slot></slot></span>
	</button>

	<a
			v-else
			v-bind:class="`hs-button${type && ' ' + assertType(type)}`"
			role="link"
			:[href]="link"
	>
		<i v-if="isIconVisible" class="hs-button__icon"
		><slot name="icon"></slot
		></i>
		<span v-if="isLabelVisible" class="hs-button__label"><slot></slot></span>
	</a>
</template>

<script>
import { Comment } from 'vue'
export default {
	name: 'HSButton',
	props: {
		link: {
			type: String,
			default: null,
		},
		isDisabled: {
			type: Boolean,
			default: false,
		},
		type: {
			type: String,
			default: '',
		},
	},
	computed: {
		isLabelVisible() {
			return (
				this.$slots.default &&
				this.$slots.default().findIndex((o) => o.type !== Comment) !== -1
			)
		},
		isIconVisible() {
			return (
				this.$slots.icon &&
				this.$slots.icon().findIndex((o) => o.type !== Comment) !== -1
			)
		},
		href() {
			return this.isDisabled ? null : 'href'
		},
	},
	methods: {
		assertType(type) {
			const finalTypes = []
			type.split(' ').forEach((type) => {
				finalTypes.push('is-' + type)
			})
			return finalTypes.join(' ')
		},
	},
}
</script>

<style lang="scss" scoped>
// Alterations
.hs-button {
	--hs-button-width: auto;
	flex-flow: row nowrap;
}
</style>
