// src/ui/react/CLBFormField/index.tsx
import React from 'react';

interface CLBFormFieldProps {
	label: string;
	helper?: string;
	type?: string;
	name?: string;
	placeholder?: string;
	rows?: number;
	isRequired?: boolean;
	isDisabled?: boolean;
	isReadonly?: boolean;
}

// @ts-ignore
const CLBFormField: React.FC<CLBFormFieldProps> = ({label, helper, type, name, placeholder, rows, isRequired, isDisabled, isReadonly}) => {
	return (
		// @ts-ignore
		<label className="hs-form-field is-filled">
			<span className="hs-form-field__label">{label}</span>
			{type !== 'textarea' &&
				<input required={isRequired} className="hs-form-field__input" name={name} type={type} placeholder={placeholder} disabled={isDisabled} readOnly={isReadonly} />
			}
			{type == 'textarea' &&
				<textarea className="hs-form-field__input" required={isRequired} rows={rows} name={name} placeholder={placeholder} disabled={isDisabled} readOnly={isReadonly} />
			}
			<span className="hs-form-field__helper">{helper}</span>
		</label>
  );
};

export default CLBFormField;

// src/ui/vue/CLBFormField.vue
<template>
	<label class="hs-form-field is-filled">
		<span class="hs-form-field__label">{{ label }}</span>
		<input v-if="type !== 'textarea'" :required="isRequired" class="hs-form-field__input" :name="name" :type="type" :placeholder="placeholder" :disabled="isDisabled" :readonly="isReadonly" />
		<textarea v-else class="hs-form-field__input" :required="isRequired" :rows="rows" :name="name" :placeholder="placeholder" :disabled="isDisabled" :readonly="isReadonly" />
	  <span v-if="helper" class="hs-form-field__helper">{{ helper }}</span>
	</label>
</template>

<script lang="ts">
export default {
	name: 'CLBFormField',
	props: {
		label: {
			type: String,
			required: true
		},
		name: {
			type: String,
			required: true
		},
		type: {
			type: String,
			required: true
		},
		helper: {
			type: String,
		},
		placeholder: {
			type: String,
		},
		rows: {
			type: Number,
			default: 5
		},
		isRequired: {
			type: Boolean,
			default: false
		},
		isDisabled: {
			type: Boolean,
			default: false
		},
		isReadonly: {
			type: Boolean,
			default: false
		}
	}
}
</script>
