// src/ui/svelte/CLBLink.svelte
<script lang="ts">
	export let link: string|undefined
	const target: string|undefined = link && _assertTarget(link)

	function _assertTarget(link: string): string {
		const _isExternalLink = (link: string): boolean =>
			!!(link.startsWith('http://') || link.startsWith('https://'))
		return _isExternalLink(link) ? '_blank' : '_self'
	}
</script>

<a href={link} class="hs-link" {target}>
	<slot />
</a>

// src/ui/react/CLBLink/index.tsx
import React from 'react';

interface CLBLinkProps {
	link: string;
  children?: React.ReactNode|string;
}

const CLBLink: React.FC<CLBLinkProps> = ({link, children}) => {

	const isLinkExternal: boolean = !!(link.startsWith('http://') || link.startsWith('https://'));

  return (
		<a href={link} className="hs-link" target={isLinkExternal ? '_blank' : '_self'}>
			{children}
		</a>
  );
};

export default CLBLink;
