// src/ui/react/CLBFormField/index.tsx
import React from 'react';

interface CLBFormFieldProps {
	label: string;
	helper?: string;
	type?: string;
	name?: string;
	placeholder?: string;
	rows?: number;
	isRequired?: boolean;
	isDisabled?: boolean;
	isReadonly?: boolean;
}

// @ts-ignore
const CLBFormField: React.FC<CLBFormFieldProps> = ({label, helper, type, name, placeholder, rows, isRequired, isDisabled, isReadonly}) => {
	return (
		// @ts-ignore
		<label className="hs-form-field is-filled">
			<span className="hs-form-field__label">{label}</span>
			{type !== 'textarea' &&
				<input required={isRequired} className="hs-form-field__input" name={name} type={type} placeholder={placeholder} disabled={isDisabled} readOnly={isReadonly} />
			}
			{type == 'textarea' &&
				<textarea className="hs-form-field__input" required={isRequired} rows={rows} name={name} placeholder={placeholder} disabled={isDisabled} readOnly={isReadonly} />
			}
			<span className="hs-form-field__helper">{helper}</span>
		</label>
  );
};

export default CLBFormField;

// src/ui/svelte/CLBFormField.svelte
<script lang="ts">
	import { handleVariants } from '../lib'

	export let label: string
	export let name: string
	export let type: string
	export let inputType: string = 'text'
	export let placeholder: string = ''
	export let helper: string
	export let rows: number = 5
	export let isRequired: boolean
	export let isDisabled: boolean
	export let isReadonly: boolean

	function _assertType(type: string): string {
		return handleVariants(type)
	}
</script>

<label class={`hs-form-field${type ? ' ' + _assertType(type) : ''}`}>
	<span class="hs-form-field__label">{label}</span>
	{#if inputType && inputType !== 'textarea'}
		<input
			required={isRequired}
			class="hs-form-field__input"
			{name}
			type={inputType}
			{placeholder}
			disabled={isDisabled}
			readonly={isReadonly}
		/>
	{:else}
		<textarea
			class="hs-form-field__input"
			required={isRequired}
			{rows}
			{name}
			{placeholder}
			disabled={isDisabled}
			readonly={isReadonly}
		/>
	{/if}

	{#if helper}
		<span class="hs-form-field__helper">{helper}</span>
	{/if}
</label>
