// src/ui/vue/CLBLink.vue
<template>
	<a :href="link" class="hs-link" :target="assertTarget(link)">
		<slot />
	</a>
</template>

<script lang="ts">
export default {
	name: 'CLBLink',
	props: {
		link: {
			type: String,
			required: true,
		},
	},
	methods: {
		assertTarget(link: string): string {
			const _isExternalLink = (link: string): boolean =>
				!!(link.startsWith('http://') || link.startsWith('https://'))
			return _isExternalLink(link) ? '_blank' : '_self'
		},
	},
}
</script>

// src/ui/svelte/CLBLink.svelte
<script lang="ts">
	export let link: string|undefined
	const target: string|undefined = link && _assertTarget(link)

	function _assertTarget(link: string): string {
		const _isExternalLink = (link: string): boolean =>
			!!(link.startsWith('http://') || link.startsWith('https://'))
		return _isExternalLink(link) ? '_blank' : '_self'
	}
</script>

<a href={link} class="hs-link" {target}>
	<slot />
</a>
