// src/ui/vue/CLBRadio.vue
<template>
	<label :class="`hs-tick-field${type ? ' ' + assertType(type) : ''}${isDisabled ? ' is-disabled' : ''}`">
		<input
			class="hs-tick-field__input"
			type="radio"
			:id="id || value"
			:name="name"
			:value="value"
			@change="onChange"
			:checked="isChecked"
			:disabled="isDisabled"
		/>
		<img
			v-if="media"
			class="hs-tick-field__sprite"
			:src="media"
			width="32"
			height="32"
			:alt="mediaAlt"
		/>
		<span style="display: flex; flex-flow: column nowrap; align-items: start">
			<span class="hs-tick-field__label">{{ label }}</span>
			<span class="hs-tick-field__helper">{{ helper }}</span>
		</span>
	</label>
</template>

<script lang="ts">
export default {
	name: 'CLBRadio',
	props: {
		name: String,
		id: String,
		value: String,
		type: String,
		label: String,
		helper: String,
		media: String,
		mediaAlt: String,
		isChecked: Boolean,
		isDisabled: Boolean,
		onChange: Function,
	},
	methods: {
		assertType(type: string): string {
			const finalTypes: string[] = []
			type.split(' ').forEach((type) => {
				finalTypes.push('is-' + type)
			})
			return finalTypes.join(' ')
		},
	},
}
</script>

// src/ui/svelte/CLBRadio.svelte
<label class={`hs-tick-field${type ? ' ' + _assertType(type) : ''}${isDisabled ? ' is-disabled' : ''}`}>
	<input
		class="hs-tick-field__input"
		type="radio"
		id={id}
		name={name}
		value={value}
		on:change={onChange}
		checked={isChecked}
		disabled={isDisabled}
	/>
	{#if media}
		<img
			class="hs-tick-field__sprite"
			src={media}
			width="32"
			height="32"
			alt={mediaAlt}
		/>
	{/if}
	<span style="display: flex; flex-flow: column nowrap; align-items: start">
		<span class="hs-tick-field__label">{label}</span>
		<span class="hs-tick-field__helper">{helper}</span>
	</span>
</label>

<script lang="ts">
	export let id: string;
	export let name: string;
	export let value: string;
	export let type: string;
	export let label: string;
	export let helper: string;
	export let media: string;
	export let mediaAlt: string;
	export let isChecked: boolean;
	export let isDisabled: boolean;
	export let onChange: (...args: any) => void;

	function _assertType(type: string): string {
		const finalTypes: string[] = []
		type.split(' ').forEach((type) => {
			finalTypes.push('is-' + type)
		})
		return finalTypes.join(' ')
	};
</script>
